framework_systempackages_extra:
  - javax.annotation.processing
  - org.apache.felix.gogo.runtime
  - org.apache.felix.gogo.command
  - org.apache.commons.logging
  - ru.babaninnv.codegen.plugins.service
  - ru.babaninnv.codegen.plugin.templator.commands
  - ru.babaninnv.codegen.plugin.templator.configurations
  - groovy.lang;version="2.6"

  # GROOVY
  - org.codehaus.groovy;version="2.6"
  - org.codehaus.groovy.control;version="2.6"
  - org.codehaus.groovy.tools;version="2.6"
  - org.codehaus.groovy.runtime;version="2.6"
  - org.codehaus.groovy.runtime.callsite;version="2.6"
  - org.codehaus.groovy.ast;version="2.6"
  - org.codehaus.groovy.classgen;version="2.6"
  - org.codehaus.groovy.classgen.asm;version="2.6"
  - org.codehaus.groovy.reflection;version="2.6"
  - org.codehaus.groovy.reflection.android;version="2.6"
  - org.codehaus.groovy.asm;version="2.6"
  - org.codehaus.groovy.runtime.metaclass;version="2.6"
  - org.codehaus.groovy.runtime.wrappers;version="2.6"

  # SPRING
  - org.springframework.beans.factory.annotation
  - org.springframework.beans.factory.config
  - org.springframework.context
  - org.springframework.context.annotation
  - org.springframework.core.io
  - org.springframework.core.type.filter
  - org.springframework.stereotype
  # LOGGER
  - org.slf4j;version="1.7.19"
  # YAML
  - org.yaml;version="1.17"
  - org.yaml.snakeyaml;version="1.17"
  
  # APACHE COMMONS
  - org.apache.commons.io;version="2.4"
  - org.apache.commons.lang3;version="3.4"
  - org.apache.commons.lang3.builder;version="3.4"
  - org.apache.commons.collections4;version="4.1"
  # GOOGLE
  - com.google.common.collect;version="19.0"

bundles_folder: ${APP_HOME}/bundles
bundles: 
  - org.apache.felix.gogo.runtime-0.16.2.jar
  - org.apache.felix.gogo.shell-0.12.0.jar
  - codegen-templator-plugin-1.0.0.jar
templates_sources_folder: ${APP_HOME}/templates/src/main/java
templates_classes_folder: ${APP_HOME}/templates/build/result-templates-classes
templates_java_sources_folder: ${APP_HOME}/templates/src/main/java
templates_groovy_sources_folder: ${APP_HOME}/templates/src/main/groovy
templates_resources_folder: ${APP_HOME}/templates/src/main/resources"
templates_classes_folder: ${APP_HOME}/templates/build/result-templates-classes
