framework_systempackages_extra: 
  - ru.babaninnv.codegen.plugins.service
  - org.apache.felix.shell
  - org.apache.felix.gogo.command
bundles_folder: 
bundles: 
  - org.apache.felix.gogo.runtime-0.16.2.jar
  - org.apache.felix.gogo.shell-0.12.0.jar
  - simple-plugin.jar
  