framework_systempackages_extra:
  - javax.annotation.processing
  - org.apache.felix.gogo.runtime
  - org.apache.felix.gogo.command
  - org.apache.commons.logging
  - ru.babaninnv.codegen.plugins.service
  - ru.babaninnv.codegen.plugin.templator.commands
  - ru.babaninnv.codegen.plugin.templator.configurations
  # SPRING
  - org.springframework.beans.factory.annotation
  - org.springframework.beans.factory.config
  - org.springframework.context
  - org.springframework.context.annotation
  - org.springframework.core.io
  - org.springframework.core.type.filter
  - org.springframework.stereotype
  # LOGGER
  - org.slf4j
  # YAML
  - org.yaml
  - org.yaml.snakeyaml
  # APACHE COMMONS
  - org.apache.commons.io
  - org.apache.commons.lang3
  - org.apache.commons.lang3.builder
  - org.apache.commons.collections4
  # GOOGLE
  - com.google.common.collect
bundles_folder: c:/Users/BabaninN/IdeaProjects/codegen-parent/codegen/bundles
bundles: 
  - org.apache.felix.gogo.runtime-0.16.2.jar
  - org.apache.felix.gogo.shell-0.12.0.jar
  - codegen-templator-plugin.jar